### ISSUE TITLE
`Bitbucket#validate()` always return true?

### ISSUE THREAD

**Issue by momocow** [milewski/webhook-exec#2]
[As the official document.](https://confluence.atlassian.com/bitbucketserver054/managing-webhooks-in-bitbucket-server-939508605.html#ManagingwebhooksinBitbucketServer-Securingyourwebhook)

Nice and clear code of this module.
I will appreciate it if the validation of Bitbucket can be implemented.
Thanks.

**Comment by momocow** [comment]
Maybe I'll fork a copy of this repo myself since I would like to use it as a module rather than a CLI command.

**Comment by milewski** [comment]
Uhm.. at the time when i built this i was unclear how the bitbucket webhook auth worked... thanks for that link.. seems it is all i need to implement the bitbucket validation.

**Comment by momocow** [comment]
I am testing on it.
Maybe I'll send a PR if I succeed.

**Comment by momocow** [comment]
Unfortunately I failed. 😢 

I was wrong since the above link is for **Bitbucket server**, not for **Bitbucket cloud**.

Here is the header from my dummy Bitbucket repository, which shows no `x-hub-signature` field to perform validation.

Headers|Values
-- | --
X-Request-UUID | *skipped*
X-Event-Key | repo:push
User-Agent | Bitbucket-Webhooks/2.0
X-Attempt-Number | 1
X-Hook-UUID | *skipped*
Content-Type | application/json

**Comment by momocow** [comment]
To sum up, no validation can be perform for Bitbucket cloud.

By the way, I think the `User-Agent` field should be checked also, and the `server` option can be multiple choices.
(Imagine a scenario that the webhook-exec server handles repositories from different remote Git hosts)

**Comment by milewski** [comment]
oh yeah now it reminded me why i just returned true.... 

![image](https://user-images.githubusercontent.com/2874967/37022434-fa11a5a4-215d-11e8-8edb-ce9e90ac3761.png)

i also don't see any field to set secret or anything... i think we just cant authenticate webhooks in bitbucket...

**Comment by momocow** [comment]
Agree.
